require("pack.autopairs")
require("pack.cmp")
require("pack.harpoon")
require("pack.lspconfig")
require("pack.lualine")
require("pack.mason")
require("pack.mini")
require("pack.oil")
require("pack.telescope")
require("pack.theme")
require("pack.treesitter")
require("pack.undotree")

--require("pack.jdtls")
