[colors.primary]
background = "#181818"
foreground = "#e4e4e4"

[colors.normal]
black   = "#453D41"
red     = "#ff5059"
green   = "#73d936"
yellow  = "#ffdd33"
blue    = "#96a6C8"
magenta = "#9d94c6"
cyan    = "#1793d1"
white   = "#e4e4e4"

[colors.bright]
black   = "#453D41"
red     = "#ff5059"
green   = "#73d936"
yellow  = "#ffdd33"
blue    = "#96A6C8"
magenta = "#9d94c6"
cyan    = "#1793D1"
white   = "#e4e4e4"
