"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
palette = 'gruber-darker'
scan_timeout = 1000

# [╭─](bold green)\
format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$direnv\
$env_var\
$custom\
$cmd_duration\
$jobs\
$container\
$netns\
$status\
$shell\
$fill\
$all\
$line_break\
$character\
$sudo"""
# [╰─](bold green)\

[fill]
symbol = ' '

[direnv]
disabled = true

[package]
disabled = true

[os]
disabled = false
# format = "[$symbol]($style)"
format = ""
style = "bold cyan"

[os.symbols]
Windows = " "
Arch = " "


[character]
success_symbol = '[](green)'
error_symbol = '[](red)'

[cmd_duration]
format = ' [ $duration](bold magenta) '
show_milliseconds = true

[username]
show_always = true
style_user = "bold yellow"
style_root = "bold orange"
# format = '[ $user [on](italic) ]($style)'
format = ""

[hostname]
ssh_only = false
disabled = false
ssh_symbol = "🌐"
style = "bold orange"
# format = "[$ssh_symbol$hostname [in](italic) ]($style)"
format = ""

[directory]
truncation_symbol = ''
read_only = " "
style = 'bold blue'

[git_branch]
symbol = ""
format = '[at](italic) [$symbol$branch(:$remote_branch)](bold #8E3728)'

[git_status]
format = "[(\\[$untracked$modified$staged\\] [$ahead_behind](red))](#8E3728)"
style = 'bold #8E3728'
untracked = "[?](bold red)"
modified = "[!](bold yellow)"
staged = "[+](bold green)"

[status]
disabled = false
format = '[$status](bold red) '


[docker_context]
format = ' [ $context](bold blue) '

[dotnet]
format = '[ ($version )](bold blue) '
version_format = 'v${major}.${minor}'

[golang]
format = '[ $version](bold cyan) '
version_format = 'v${major}.${minor}'

[gradle]
format = '[ ($version)](bold green) '
version_format = 'v${major}.${minor}'

[java]
format = '[ ${version}](bold red) '
version_format = 'v${major}.${minor}'

[lua]
format = '[ $version](bold yellow) '
version_format = 'v${major}.${minor}'

[nodejs]
format = ' [ ($version)](bold green) '
version_format = 'v${major}.${minor}'

[pulumi]
format = ' [󰆦 ($username@)$stack](bold yellow) '
version_format = 'v${major}.${minor}'

[python]
format = ' [ ${pyenv_prefix}(${version} )(\($virtualenv\) )](bold yellow) '
version_format = 'v${major}.${minor}'

[rust]
format = ' [󱘗 $version](bold orange) '
version_format = 'v${major}.${minor}'

[terraform]
format = ' [󰆩 $workspace](bold magenta) '
version_format = 'v${major}.${minor}'

[palettes.gruber-darker]
black   = "#181818"
red     = "#ff5059"
green   = "#73d936"
yellow  = "#ffdd33"
orange  = "#cb8b3e"
blue    = "#96A6C8"
magenta = "#9d94c6"
cyan    = "#1793D1"
white   = "#f4f4ff"
