preload = ~/.config/hypr/wallpapers/wallhaven-pol82j.png

wallpaper {
	monitor = eDP-1
	path = ~/.config/hypr/wallpapers/wallhaven-pol82j.png
}
wallpaper {
	monitor = HDMI-A-1
	path = ~/.config/hypr/wallpapers/wallhaven-pol82j.png
}

# preload = ~/.config/hypr/wallpapers/wallhaven-yq769k.png
#
# wallpaper {
# 	monitor = eDP-1
# 	path = ~/.config/hypr/wallpapers/wallhaven-yq769k.png
# }
# wallpaper {
# 	monitor = HDMI-A-1
# 	path = ~/.config/hypr/wallpapers/wallhaven-yq769k.png
# }
splash = false
