general {
	grace = 0
	no_fade_in = false
	disable_loading_bar = false
}

background {
	blur_passes = 3
	path = $HOME/.config/hypr/wallpapers/wallhaven-pol82j.png
}

label {
	text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
	position = 0, 350
	color = rgba(216, 222, 233, 0.70)
	font_size = 25
	font_family = FiraCode Nerd Font
}

label {
	monitor =
		text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
		position = 0, 250
		color = rgba(216, 222, 233, 0.70)
		font_size = 120
		font_family = FiraCode Nerd Font Bold
}

shape {
	size = 300, 60
	color = rgba(255, 255, 255, .1)
	rounding = -1
	position = 0, -130
}

label {
	text =  $USER
	color = rgba(216, 222, 233, 0.80)
	position = 0, -130
	font_size = 18
	font_family = JetBrainsMono Nerd Font Propo
}

input-field {
	placeholder_text = 
	hide_input = false
	size = 300, 60
	position = 0, -210
	fade_on_empty = false
	inner_color = rgba(255, 255, 255, 0.1)
	font_color = rgb(200, 200, 200)
	font_family = JetBrainsMono Nerd Font Propo
}

label {
	text = cmd[update:1000] echo "$(~/.config/hypr/scripts/songdetail.sh)"
	position = 0, 50
	valign = bottom
	font_size = 18
	color = rgba(255, 255, 255, 0.6)
	font_family = JetBrainsMono Nerd Font
}
