$terminal				 = kitty
$file_manager		 = nautilus
$swaync					 = swaync-client -t -sw
$waybar					 = pkill waybar || waybar
$menu						 = pkill rofi || rofi -show
$wlogout				 = pkill wlogout || wlogout
$hyprshot_region = hyprshot -m region --clipboard-only
$hyprshot_screen = hyprshot -m active -m output --clipboard-only
