windowrule {
  name = float-waydroid
	match:class = ^waydroid.com
  float = true
}

windowrule {
  name = float-medium
	match:title = ^(kitty|Network\ Connections|Bluetooth\ Devices|Volume\ Control)$
  float = true
	size = 950 550
}

windowrule {
  name = float-big
	match:title = ^(btop|nvtop|Calendar)$
  float = true
	size = 1450 750
}

layerrule {
	name = rofi-animation
	match:namespace = rofi
	blur = on
	dim_around = on
	animation = slide left
}

layerrule {
	name = wlogout-animation
	match:namespace = logout_dialog
	blur = on
	animation = slide bottom
}
