general {
    gaps_in = 5
    gaps_out = 20
    border_size = 0
    allow_tearing = false
    layout = master
}

dwindle {
		pseudotile = true
		preserve_split = true
}

master {
    new_status = slave
		new_on_top = true
}

source = ./animations.conf
source = ./decorations.conf
